version: '3.3'

services:
    #esta es la base de datos
    postgres:
      image: postgres:13
      environment:
        - POSTGRES_DB=my_db
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=123456
      ports:
        - '5432:5432'
      volumes:
        - ./postgres_data:/var/lib/postgresql/data

    #este es el visualizador de la DB postgres
    pgadmin:
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=root@admin.com
        - PGADMIN_DEFAULT_PASSWORD=root
      ports:
        - "5050:80"
      depends_on:
        - postgres

    #esta es la base de datos mysql, osea con estas directivas es como se crea la base de datos en el contenedor
    mysql:
      image: mysql:8
      environment:
        - MYSQL_DB=my_db
        - MYSQL_USER=root
        - MYSQL_ROOT_PASSWORD=123456      
      ports:
        - '3307:3307'
      volumes:
        - ./mysql_data:/var/lib/mysql

    #este es el visualizador de la DB mysql
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        - MYSQL_ROOT_PASSWORD=123456 
        - PMA_HOST=mysql
      ports:
        - "8080:80"
      depends_on:
        - mysql
